Repository coder/code-server, pull requests merged in 2021-12, with the labels that each got.

#4548 Proxy path fixes
  src/common/http.ts
  src/node/http.ts
  src/node/main.ts
  src/node/routes/login.ts
  src/node/routes/logout.ts
  src/node/routes/vscode.ts
  src/node/util.ts
  test/unit/common/http.test.ts
  test/utils/globalSetup.ts
  vendor/package.json
  vendor/yarn.lock
Labels: bug, enhancement

#4571 docs: update sections around VS Code fork
  docs/CONTRIBUTING.md
  docs/MAINTAINING.md
Labels: docs, squash when passing

#4546 chore: replace eslint-import-resolver-alias with resolver-typescript
  .eslintrc.yaml
  package.json
  src/node/http.ts
  src/node/routes/pathProxy.ts
  src/node/wsRouter.ts
  test/unit/node/proxy.test.ts
  test/unit/node/test-plugin/.eslintrc.js
  test/unit/node/test-plugin/.eslintrc.yaml
  yarn.lock
Labels: chore

#4622 docs: add section for iOS
  docs/ios.md
  docs/manifest.json
Labels: docs, squash when passing

#4579 Support browsers from before 2020
  tsconfig.json
Labels: chore

#4628 fix: add --clobber to release-github-assets script
  ci/build/release-github-assets.sh
Labels: squash when passing, chore

#4621 docs: add section for Android
  docs/android.md
  docs/manifest.json
Labels: docs, squash when passing

#4641 Add codeowner group for new name
  .github/CODEOWNERS
Labels: squash when passing

#4627 docs: fix install.sh link
  docs/install.md
Labels: docs, squash when passing

#4632 fix: add codeServerVersion to vscode/product.json
  ci/build/build-release.sh
  package.json
  vendor/package.json
  vendor/yarn.lock
Labels: bug, squash when passing
