Repository coder/code-server, pull requests merged in 2021-04, with the labels that each got.

#3025 chore: fix typo in install.sh
  install.sh
Labels: new contributor

#3026 dev(ranger): add action for upstream issues
  .github/ranger.yml
Labels: merge when passing

#3043 chore(deps): limit xdg-basedir updates
  .github/dependabot.yml
Labels: dependencies

#3134 refactor: remove debian10/Dockerfile and update CONTRIBUTING
  ci/images/centos7/Dockerfile
  ci/images/debian10/Dockerfile
  docs/CONTRIBUTING.md
Labels: merge when passing

#3133 refactor(testing): migrate to playwright-test from jest-playwright
  .github/workflows/ci.yaml
  .gitignore
  ci/dev/test-e2e.sh
  test/config.ts
  test/e2e/browser.test.ts
  test/e2e/globalSetup.test.ts
  test/e2e/login.test.ts
  test/e2e/loginPage.test.ts
  test/e2e/logout.test.ts
  test/e2e/openHelpAbout.test.ts
  test/jest.e2e.config.ts
  test/package.json
  test/yarn.lock
Labels: merge when passing

#3148 docs: add security policy
  docs/SECURITY.md
Labels: merge when passing

#3194 feat(testing): add codecov to generate test coverage reports
  .github/workflows/ci.yaml
  package.json
  yarn.lock
Labels: merge when passing, testing

#3200 feat(testing): add tests for registerServiceWorker
  src/browser/register.ts
  test/unit/register.test.ts
  test/unit/util.test.ts
Labels: merge when passing, testing

#3217 docs(guide.md): add `caddy` example for serving from sub-path
  docs/guide.md
Labels: docs, merge when passing, new contributor

#3223 chore(deps): update dependencies with CVEs
  lib/vscode/build/yarn.lock
  lib/vscode/yarn.lock
Labels: dependencies

#3227 docs(readme): refactor to use codecov shield
  README.md
  ci/README.md
  ci/build/release-prep.sh
  package.json
Labels: docs, merge when passing, testing

#3169 feat(testing): add e2e tests for code-server and terminal
  src/node/constants.ts
  src/node/socket.ts
  src/node/util.ts
  test/e2e/browser.test.ts
  test/e2e/codeServer.test.ts
  test/e2e/globalSetup.test.ts
  test/e2e/login.test.ts
  test/e2e/logout.test.ts
  test/e2e/models/CodeServer.ts
  test/e2e/openHelpAbout.test.ts
  test/e2e/terminal.test.ts
  test/unit/cli.test.ts
  test/unit/constants.test.ts
  test/unit/socket.test.ts
  test/unit/update.test.ts
  test/utils/constants.ts
Labels: testing

#3230 refactor(testing): fix flaky terminal test
  test/e2e/models/CodeServer.ts
  test/e2e/terminal.test.ts
Labels: merge when passing, testing

#3244 chore: ignore 15.x @types/node updates
  .github/dependabot.yml
Labels: dependencies, merge when passing

#3229 feat(security): add code-scanning with CodeQL
  .github/codeql-config.yml
  .github/dependabot.yml
  .github/workflows/codeql-analysis.yml
Labels: merge when passing, security

#3250 chore(build): compile vscode+extensions in parallel
  ci/build/build-vscode.sh
Labels: ci

#3228 docs(maintaining): use milestones over boards
  ci/dev/fmt.sh
  docs/MAINTAINING.md
  test/unit/register.test.ts
Labels: docs, merge when passing

#3251 docs(termux): add workaround for Android backspace issue
  ci/dev/fmt.sh
  docs/install.md
  docs/termux.md
Labels: docs, merge when passing

#3247 docs(faq): add entry for accessing OSX folders
  docs/FAQ.md
Labels: docs

#3260 fix(deps): remove eslint-plugin-jest-playwright
  .eslintrc.yaml
  package.json
Labels: dependencies, merge when passing

#3263 fix(testing): reduce flakiness of terminal.test.ts and use 1 worker for e2e tests
  test/config.ts
  test/e2e/terminal.test.ts
  yarn.lock
Labels: testing
