Repository coder/code-server, pull requests merged in 2021-10, with the labels that each got.

#4273 chore(helm-chart): bump to 1.0.5
  ci/helm-chart/Chart.yaml
Labels: chore

#4274 docs: update section around testing
  docs/CONTRIBUTING.md
  docs/MAINTAINING.md
Labels: docs, testing

#4290 chore(vscode): update to latest commit of fork
  .github/workflows/ci.yaml
  vendor/package.json
  vendor/yarn.lock
Labels: chore

#4301 Fix marketplace in CLI
  src/node/main.ts
  vendor/package.json
  vendor/yarn.lock
Labels: bug

#4306 fix: revert CI change + fix broken tests
  .github/workflows/ci.yaml
  src/node/routes/index.ts
  test/unit/node/routes/static.test.ts
Labels: ci, testing, chore

#4293 Fix: use pipe to spawn http server process to enable logs pipe to files
  src/node/wrapper.ts
Labels: bug

#4307 update comparisons in FAQ
  docs/FAQ.md
Labels: docs

#4309 feat(cli): add tests for password, hashed-password
  test/unit/node/cli.test.ts
Labels: testing

#4284 feat(cli): add test for readSocketPath
  .github/workflows/ci.yaml
  src/node/cli.ts
  src/node/util.ts
  test/unit/node/cli.test.ts
Labels: testing
