Repository coder/code-server, pull requests merged in 2021-07, with the labels that each got.

#3700 fix: add timeouts to CI jobs
  .github/workflows/ci.yaml
Labels: chore, ci

#3698 fix(isHashMatch): check that hash starts with $
  src/node/util.ts
  test/unit/node/util.test.ts
Labels: chore, testing

#3695 fix: escape error.message on login failure
  src/node/http.ts
  src/node/routes/login.ts
  src/node/util.ts
  test/unit/node/util.test.ts
  test/unit/routes/login.test.ts
Labels: security

#3697 docs(guide): add WebSockets to requirements
  docs/guide.md
Labels: docs

#3706 docs(install): add troubleshooting node issues
  docs/install.md
Labels: docs

#3707 fix: update install script for alpine
  install.sh
Labels: bug, docs

#3711 chore: fix broken link in install.sh
  install.sh
Labels: docs

#3714 feat(test): check login.ts when base missing
  test/browser/pages/login.test.ts
Labels: testing

#3728 fix: openFolder button on Explorer panel
  lib/vscode/src/vs/workbench/contrib/files/browser/explorerViewlet.ts
Labels: bug

#3729 chore: remove unused dependencies
  package.json
  test/package.json
  test/yarn.lock
  yarn.lock
Labels: chore, dependencies

#3726 docs(guide): add note about configuration for NGINX
  docs/guide.md
Labels: docs

#3743 feat: add more tests for browser/pages/vscode
  src/browser/pages/vscode.ts
  test/unit/browser/vscode.test.ts
Labels: testing

#3749 fix(dependabot): ignore major updates for node
  .github/dependabot.yml
Labels: dependencies

#3759 docs(faq): add line about password login limits
  docs/FAQ.md
Labels: docs

#3756 refactor(docs): clean up and restructure
  docs/CONTRIBUTING.md
  docs/FAQ.md
  docs/MAINTAINING.md
  docs/README.md
  docs/SECURITY.md
  docs/guide.md
  docs/install.md
  docs/ipad.md
  docs/npm.md
  docs/requirements.md
  docs/termux.md
  docs/triage.md
  docs/upgrade.md
Labels: docs

#3751 fix: check uri.path is string in pathToFsPath
  src/node/util.ts
  test/unit/node/util.test.ts
Labels: security, testing

#3769 refactor: clean up testing files
  test/unit/browser/pages/login.test.ts
  test/unit/browser/pages/vscode.test.ts
  test/unit/browser/register.test.ts
  test/unit/browser/serviceWorker.test.ts
  test/unit/node/util.test.ts
Labels: chore, testing

#3819 chore: update guides.md header to Accessing Web Services
  docs/guide.md
Labels: docs

#3831 chore: Update dependency requirements. Fix node version manager.
  .node-version
  .nvmrc
  docs/CONTRIBUTING.md
Labels: chore, docs, enhancement

#3832 chore: update coverage thresholds
  .github/codecov.yml
  package.json
Labels: chore

#3760 feat: add registerRequireOnSelf on function
  src/browser/pages/vscode.ts
  test/unit/browser/pages/vscode.test.ts
  test/unit/node/util.test.ts
Labels: testing

#3829 Fix "serviceWorker.js" path
  src/browser/register.ts
  test/unit/browser/register.test.ts
Labels: bug

#3840 docs(install): add uninstall instructions
  docs/install.md
Labels: docs

#3846 feat: add tests for shouldEnableProxy
  src/node/proxy_agent.ts
  test/unit/helpers.test.ts
  test/unit/node/proxy_agent.test.ts
  test/utils/helpers.ts
Labels: testing

#3866 refactor: clean up test file structure
  ci/dev/test-unit.sh
  docs/CONTRIBUTING.md
  test/unit/browser/pages/login.test.ts
  test/unit/browser/register.test.ts
  test/unit/common/emitter.test.ts
  test/unit/common/http.test.ts
  test/unit/common/util.test.ts
  test/unit/node/cli.test.ts
  test/unit/node/constants.test.ts
  test/unit/node/plugin.test.ts
  test/unit/node/proxy.test.ts
  test/unit/node/routes/health.test.ts
  test/unit/node/routes/login.test.ts
  test/unit/node/routes/static.test.ts
  test/unit/node/socket.test.ts
  test/unit/node/test-plugin/.eslintrc.yaml
  test/unit/node/test-plugin/.gitignore
  test/unit/node/test-plugin/Makefile
  test/unit/node/test-plugin/package.json
  test/unit/node/test-plugin/public/icon.svg
  test/unit/node/test-plugin/public/index.html
  test/unit/node/test-plugin/src/index.ts
  test/unit/node/test-plugin/tsconfig.json
  test/unit/node/test-plugin/yarn.lock
  test/unit/node/update.test.ts
  test/unit/node/util.test.ts
Labels: chore, testing

#3858 feat: add more tests for proxy.ts
  test/unit/helpers.test.ts
  test/unit/node/proxy.test.ts
  test/utils/helpers.ts
Labels: testing
