Repository coder/code-server, pull requests merged in 2021-11, with the labels that each got.

#4288 refactor(ci): only run release workflows on released event
  .github/workflows/docker.yaml
  .github/workflows/npm-brew.yaml
Labels: chore

#4328 docs(contrib): update linux requirements
  docs/CONTRIBUTING.md
Labels: docs

#4428 chore(deps): upgrade path-parse in test/yarn.lock
  test/package.json
  test/yarn.lock
Labels: dependencies

#4438 chore(deps): fix issues identified by audit-ci
  .github/workflows/ci.yaml
  package.json
  yarn.lock
Labels: dependencies

#4439 Revert "Add linkup command to improve link functionality"
  .gitignore
  ci/build/build-code-server.sh
  ci/build/build-release.sh
  ci/build/npm-postinstall.sh
  src/node/link.ts
  src/node/main.ts
Labels: chore

#4419 Add a gist of the difference between code-server and Coder
  docs/README.md
Labels: docs

#4414 Use upstream server WIP
  .github/workflows/ci.yaml
  ci/build/build-release.sh
  ci/build/build-vscode.sh
  package.json
  src/node/cli.ts
  src/node/constants.ts
  src/node/entry.ts
  src/node/main.ts
  src/node/routes/errors.ts
  src/node/routes/index.ts
  src/node/routes/vscode.ts
  src/node/util.ts
  test/e2e/models/CodeServer.ts
  test/unit/node/app.test.ts
  test/unit/node/cli.test.ts
  test/unit/node/plugin.test.ts
  vendor/package.json
  vendor/yarn.lock
Labels: enhancement, high-priority

#4499 Spawn vscode on demand
  src/node/routes/index.ts
  src/node/routes/vscode.ts
  vendor/package.json
  vendor/yarn.lock
Labels: bug, enhancement

#4502 docs: update CONTRIBUTING with new flow
  docs/CONTRIBUTING.md
Labels: docs

#4511 feat(testing): refactor humanPath and add tests
  src/node/cli.ts
  src/node/main.ts
  src/node/routes/login.ts
  src/node/util.ts
  test/unit/node/util.test.ts
Labels: testing, squash when passing

#4515 fix NOTE.txt
  ci/helm-chart/templates/NOTES.txt
Labels: bug

#4520 Fix watcher not restarting code-server on VS Code compilation
  ci/dev/watch.ts
Labels: chore

#4509 Watcher improvements
  ci/dev/watch.ts
  package.json
  src/node/routes/vscode.ts
  src/node/util.ts
  yarn.lock
Labels: enhancement, chore

#4532 chore(codecov): add slack webhook integration
  .github/codecov.yml
Labels: squash when passing, chore

#4534 Fix issue where 404 errors are mistaken for server errors.
  src/node/routes/errors.ts
  vendor/package.json
  vendor/yarn.lock
Labels: bug

#4543 chore(deps): upgrade json-schema version to 0.4.0
  test/package.json
  test/yarn.lock
Labels: security, dependencies, squash when passing, chore

#4542 feat: add test for onLine throw error
  test/unit/node/util.test.ts
Labels: testing, squash when passing

#4562 chore: add deprecation notice for --link
  docs/README.md
  docs/link.md
  src/node/cli.ts
Labels: docs, chore
