Repository coder/code-server, pull requests merged in 2021-09, with the labels that each got.

#4085 fix(security): tar vulnerability
  lib/vscode/package.json
  lib/vscode/yarn.lock
  package.json
  test/package.json
  test/yarn.lock
  yarn.lock
Labels: security, dependencies

#4070 docs: add troubleshooting section for documentation
  docs/MAINTAINING.md
Labels: docs

#4071 fix: revert revert and add ssh back into guide docs
  docs/guide.md
  lib/vscode/package.json
  lib/vscode/yarn.lock
  package.json
  test/package.json
  test/yarn.lock
  yarn.lock
Labels: docs

#4120 Push latest Docker tag along with version tag
  ci/release-image/docker-bake.hcl
Labels: ci

#4129 fix(security): address dependency vulnerabilities
  lib/vscode/extensions/github-authentication/package.json
  lib/vscode/extensions/github-authentication/yarn.lock
  lib/vscode/package.json
  lib/vscode/yarn.lock
Labels: security, dependencies

#4099 feat: add tests for src/node/app.ts
  src/node/app.ts
  test/unit/node/app.test.ts
Labels: testing

#4131 fix(lib/vscode): update csp in webview to allow ports
  lib/vscode/src/vs/workbench/api/common/shared/webview.ts
Labels: bug

#4158 fix(security): fix ReDoS in Regex
  src/node/util.ts
Labels: security

#4144 Add docs around using duckly for collaboration
  docs/collaboration.md
  docs/manifest.json
Labels: docs

#4159 fix(codecov): use status > patch correctly
  .github/codecov.yml
Labels: testing, chore

#4044 fix(revert): move helm README to docs
  ci/helm-chart/README.md
  docs/guide.md
  docs/helm.md
  docs/install.md
  docs/manifest.json
Labels: docs

#4165 add CodeTogether docs
  docs/collaboration.md
Labels: docs

#4175 fix: comment out broken e2e test
  test/e2e/logout.test.ts
Labels: testing, chore

#4192 Make native-keymap and keytar optional dependencies
  ci/dev/postinstall.sh
  docs/MAINTAINING.md
  vendor/package.json
  vendor/yarn.lock
Labels: bug

#4170 fix(security): update set-value
  test/package.json
  test/yarn.lock
Labels: security, dependencies

#4194 feat: add test for get_nfpm_arch()
  ci/build/arch-override.json
  ci/build/build-lib.sh
  ci/build/build-packages.sh
  test/scripts/build-lib.bats
Labels: testing

#4160 feat: add tests for src/node/app.ts
  src/node/app.ts
  src/node/util.ts
  test/unit/node/__snapshots__/app.test.ts.snap
  test/unit/node/app.test.ts
Labels: testing

#4218 fix(ci): upgrade runner to ubuntu-18.04
  .github/workflows/ci.yaml
Labels: chore

#4211 feat: add tests for shouldRunVsCodeCli and bindAddrFromArgs
  src/node/cli.ts
  test/unit/node/cli.test.ts
Labels: testing

#4228 update iPad docs to reflect info in Sep 2021
  docs/ipad.md
Labels: docs

#4231 Revert "fix: run postinstall script explicitly with bash (#4116)"
  ci/build/build-release.sh
Labels: bug

#4234 docs(MAINTAINING): update release section + add team section
  docs/MAINTAINING.md
Labels: docs

#4230 fix(package.json): update node version requirements to >=14
  package.json
Labels: javascript

#4251 chore(deps): upgrade ansi-regex to 5.0.1 and tmpl to 1.0.5
  package.json
  test/package.json
  test/yarn.lock
  yarn.lock
Labels: security, dependencies, chore

#4244 Use Ingress v1 from Kubernetes v1.19 in helm chart
  ci/helm-chart/templates/ingress.yaml
Labels: enhancement

#4253 fix: update CODEOWNERS for helm-chart
  .github/CODEOWNERS
Labels: chore

#4236 fix(brew-bump.sh): add checks and handle errors
  ci/steps/brew-bump.sh
  ci/steps/steps-lib.sh
  test/scripts/steps-lib.bats
Labels: ci, testing, chore

#4265 feat(cli): add test for defaultConfigFile
  src/node/cli.ts
  test/unit/node/cli.test.ts
Labels: testing

#4254 iPad docs: add copy & paste known issue
  docs/ipad.md
Labels: os-ios

#4281 Update collaboration.md
  docs/collaboration.md
Labels: docs
