Repository coder/code-server, pull requests merged in 2021-06, with the labels that each got.

#3520 fix: ws vulnerabilities
  package.json
  yarn.lock
Labels: security

#3512 docs: move release process to MAINTAINING.md
  CHANGELOG.md
  ci/README.md
  docs/MAINTAINING.md
Labels: docs

#3516 feat(ci): add restore-keys for ci speedup
  .github/workflows/ci.yaml
  ci/build/npm-postinstall.sh
  ci/lib.sh
Labels: ci

#3468 fix(publish): update cdrci fork in brew-bump.sh
  .github/workflows/publish.yaml
  CHANGELOG.md
  ci/steps/brew-bump.sh
Labels: ci, merge when passing

#3532 docs: format 'Caddy'
  CHANGELOG.md
  docs/guide.md
Labels: docs, new contributor

#3557 chore: update .gitignore
  .gitignore
  CHANGELOG.md
Labels: chore, new contributor

#3422 fix: use sufficient computational effort for password hash
  CHANGELOG.md
  ci/build/build-standalone-release.sh
  ci/build/npm-postinstall.sh
  docs/FAQ.md
  package.json
  src/node/cli.ts
  src/node/http.ts
  src/node/routes/domainProxy.ts
  src/node/routes/index.ts
  src/node/routes/login.ts
  src/node/routes/pathProxy.ts
  src/node/routes/static.ts
  src/node/routes/vscode.ts
  src/node/util.ts
  test/config.ts
  test/package.json
  test/unit/cli.test.ts
  test/unit/node/util.test.ts
  test/yarn.lock
  typings/pluginapi.d.ts
  yarn.lock
Labels: security

#3590 chore: upgrade to Playwright 1.12 with its new test-runner
  ci/dev/test-e2e.sh
  src/node/util.ts
  test/config.ts
  test/e2e/baseFixture.ts
  test/e2e/browser.test.ts
  test/e2e/codeServer.test.ts
  test/e2e/globalSetup.test.ts
  test/e2e/login.test.ts
  test/e2e/logout.test.ts
  test/e2e/models/CodeServer.ts
  test/e2e/openHelpAbout.test.ts
  test/e2e/terminal.test.ts
  test/package.json
  test/playwright.config.ts
  test/utils/constants.ts
  test/utils/globalSetup.ts
  test/yarn.lock
Labels: new contributor, testing

#3602 fix: placeholder password in hashed password example
  docs/FAQ.md
Labels: docs

#3598 Allow code-server to identify raspberry pi 4 (armv7l)
  ci/lib.sh
Labels: bug, new contributor

#3630 docs: Update CONTRIBUTING.md
  docs/CONTRIBUTING.md
Labels: docs

#3629 docs(CONTRIBUTING): add section on testing
  CHANGELOG.md
  docs/CONTRIBUTING.md
Labels: chore, docs, testing

#3614 chore(dev): remove parcel
  .gitignore
  ci/build/build-code-server.sh
  ci/build/build-release.sh
  ci/dev/watch.ts
  package.json
  src/browser/pages/error.html
  src/browser/pages/login.html
  src/browser/pages/login.ts
  src/browser/pages/vscode.html
  src/browser/pages/vscode.ts
  tsconfig.json
  yarn.lock
Labels: chore

#3647 Update link desc to Coder.com in README
  README.md
Labels: docs

#3660 docs(MAINTAINING): update changelog process
  .github/PULL_REQUEST_TEMPLATE.md
  docs/MAINTAINING.md
Labels: docs

#3659 docs(termux): add backspace workaround for android
  docs/termux.md
Labels: docs

#3640 refactor: add func and tests for getNlsConfiguration
  src/browser/pages/vscode.ts
  test/unit/browser/vscode.test.ts
Labels: testing

#3658 chore(dev): migrate away from parcel and replace with browserify
  .github/codecov.yml
  .gitignore
  CHANGELOG.md
  ci/build/build-code-server.sh
  ci/build/build-release.sh
  ci/dev/watch.ts
  package.json
  src/browser/pages/error.html
  src/browser/pages/login.html
  src/browser/pages/login.ts
  src/browser/pages/vscode.html
  src/browser/pages/vscode.ts
  src/browser/register.ts
  test/browser/pages/login.test.ts
  tsconfig.json
  yarn.lock
Labels: chore

#3664 Parallel tests
  .github/workflows/ci.yaml
  ci/dev/test-e2e.sh
  ci/dev/watch.ts
  src/node/util.ts
  test/e2e/baseFixture.ts
  test/e2e/browser.test.ts
  test/e2e/codeServer.test.ts
  test/e2e/globalSetup.test.ts
  test/e2e/login.test.ts
  test/e2e/logout.test.ts
  test/e2e/models/CodeServer.ts
  test/e2e/openHelpAbout.test.ts
  test/e2e/terminal.test.ts
  test/playwright.config.ts
  test/unit/node/util.test.ts
  test/unit/util.test.ts
  test/utils/constants.ts
  test/utils/globalSetup.ts
  test/utils/helpers.ts
Labels: testing

#3692 Fix broken link on docs site
  docs/install.md
Labels: docs, new contributor
