Repository coder/code-server, pull requests merged in 2021-05, with the labels that each got.

#3261 feat(ci): add trivy job for security
  .github/workflows/ci.yaml
Labels: security

#3284 docs(maintaining): add triage to workflow
  docs/MAINTAINING.md
Labels: docs, merge when passing

#3277 Refactor logout
  lib/vscode/.eslintignore
  lib/vscode/src/vs/server/browser/client.ts
  lib/vscode/src/vs/server/common/cookie.ts
  lib/vscode/src/vs/server/common/util.ts
  lib/vscode/src/vs/workbench/browser/parts/titlebar/menubarControl.ts
  src/browser/register.ts
  src/common/util.ts
  src/node/app.ts
  src/node/routes/index.ts
  src/node/routes/logout.ts
  src/node/routes/vscode.ts
  test/unit/register.test.ts
  test/unit/update.test.ts
  test/unit/util.test.ts
  test/utils/httpserver.ts
  typings/ipc.d.ts
Labels: enhancement

#3288 docs(maintaining): add versioning
  docs/MAINTAINING.md
Labels: docs, merge when passing

#3287 docs(security): add section for tools
  docs/SECURITY.md
Labels: docs, security

#3286 Add flag for toggling permessage-deflate
  src/node/cli.ts
  src/node/constants.ts
  src/node/entry.ts
  src/node/main.ts
  src/node/routes/vscode.ts
  test/unit/cli.test.ts
  test/unit/health.test.ts
  test/unit/proxy.test.ts
  test/utils/integration.ts
Labels: enhancement

#3298 refactor(ci): split audit from prebuild
  .github/workflows/ci.yaml
Labels: ci

#3290 feat(testing): add test for src/node/constants.ts
  package.json
  test/unit/constants.test.ts
Labels: testing

#3297 Test static route
  test/e2e/terminal.test.ts
  test/unit/constants.test.ts
  test/unit/helpers.test.ts
  test/unit/register.test.ts
  test/unit/routes/health.test.ts
  test/unit/routes/static.test.ts
  test/unit/util.test.ts
  test/utils/constants.ts
  test/utils/helpers.ts
  test/utils/integration.ts
Labels: testing

#3309 Make sure directories exist
  lib/vscode/src/vs/platform/extensionManagement/node/extensionsScanner.ts
  lib/vscode/src/vs/server/node/server.ts
Labels: enhancement

#3308 Use ptyHostService
  lib/vscode/coder.js
  lib/vscode/src/vs/platform/terminal/node/ptyService.ts
  lib/vscode/src/vs/platform/terminal/node/terminalProcess.ts
  lib/vscode/src/vs/server/node/channel.ts
  lib/vscode/src/vs/server/node/server.ts
Labels: enhancement

#3337 docs: add changelog
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CHANGELOG.md
  ci/dev/fmt.sh
Labels: docs

#3330 Check the logged user instead of $USER
  ci/release-image/entrypoint.sh
Labels: enhancement, new contributor

#3354 chore: update CHANGELOG
  CHANGELOG.md
Labels: docs, merge when passing

#3367 chore: ignore updates to microsoft/playwright-github-action
  .github/dependabot.yml
  CHANGELOG.md
Labels: dependencies

#3376 docs(install): add raspberry pi section
  CHANGELOG.md
  docs/install.md
Labels: docs, merge when passing

#3304 fix(socket): use xdgBasedir.runtime instead of tmp
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  CHANGELOG.md
  src/node/socket.ts
  src/node/util.ts
  test/unit/node/util.test.ts
Labels: enhancement

#3378 docs(maintaining): add pull requests section
  CHANGELOG.md
  docs/MAINTAINING.md
Labels: docs

#3368 fix(ci): re-enable trivy-scan-repo
  .github/workflows/ci.yaml
  CHANGELOG.md
Labels: ci

#3375 refactor: move default PR template
  .github/PULL_REQUEST_TEMPLATE.md
  CHANGELOG.md
Labels: docs

#3377 docs(contributing): add commits section
  CHANGELOG.md
  docs/CONTRIBUTING.md
Labels: docs

#3360 docs(maintaining): add process for release managers
  .github/ISSUE_TEMPLATE/release.md
  .github/PULL_REQUEST_TEMPLATE/release_template.md
  CHANGELOG.md
  ci/README.md
  ci/build/release-prep.sh
  docs/MAINTAINING.md
Labels: chore, docs

#3396 Termux on Play Store is deprecated; replaced with F-Droid link
  docs/termux.md
Labels: docs, new contributor

#3430 fix(dependabot): limit limiter updates
  .github/dependabot.yml
Labels: dependencies

#3437 fix: use correct command to Open Folder on Welcome page
  CHANGELOG.md
  lib/vscode/src/vs/workbench/contrib/welcome/page/browser/vs_code_welcome_page.ts
Labels: squash when passing

#3438 fix(ci): update brew-bump.sh to update remote first
  CHANGELOG.md
  ci/steps/brew-bump.sh
Labels: ci

#3461 fix(ci): disable trivy-scan-image
  .github/workflows/ci.yaml
  package.json
  yarn.lock
Labels: ci

#3424 docs: add Pomerium
  docs/FAQ.md
Labels: docs, new contributor

#3460 docs: fix confusing sentence in pull requests section
  CHANGELOG.md
  docs/CONTRIBUTING.md
Labels: docs, new contributor

#3466 fix: remove CHANGELOG from fmt.sh and remove toc from CHANGELOG
  CHANGELOG.md
  ci/dev/fmt.sh
Labels: chore

#3467 docs(MAINTAINING): add information about CHANGELOG
  CHANGELOG.md
  docs/MAINTAINING.md
Labels: docs

#3465 chore: update CHANGELOG
  CHANGELOG.md
Labels: chore
