Repository coder/code-server, pull requests merged in 2022-10, with the labels that each got.

#5633 feat: add customization options for the login page
  src/browser/pages/login.html
  src/node/cli.ts
  src/node/routes/login.ts
  test/unit/node/cli.test.ts
  test/unit/node/routes/login.test.ts
Labels: hacktoberfest-accepted

#5624 fix: add handle for resolveExternalUri
  patches/proxy-uri.diff
  patches/service-worker.diff
  test/e2e/extensions/ms-ceintl.vscode-language-pack-es-1.70.0/package.json
  test/e2e/extensions/test-extension/extension.ts
  test/e2e/extensions/test-extension/package.json
  test/playwright.config.ts
Labels: rebase when passing

#5697 chore: update minimatch
  package.json
  yarn.lock
Labels: dependencies

#5703 fix: pin azure/setup-helm to v3.10.1
  .github/workflows/build.yaml
Labels: rebase when passing

#5700 chore(deps): update prettier and eslint
  package.json
  src/node/cli.ts
  yarn.lock
Labels: dependencies, rebase when passing

#5704 chore(deps): downgrade argon2 to 0.29.0
  package.json
  yarn.lock
Labels: rebase when passing

#5713 release: 4.8.1-rc.1
  package.json
  patches/telemetry.diff
  test/unit/node/test-plugin/package.json
Labels: rebase when passing

#5721 chore: prettierignore updates and setup-helm upgrade
  .github/workflows/build.yaml
  .prettierignore
Labels: rebase when passing

#5707 feat: customize getting started page
  docs/FAQ.md
  patches/getting-started.diff
  patches/series
  src/node/cli.ts
  test/unit/node/cli.test.ts
Labels: rebase when passing
