Repository coder/code-server, pull requests merged in 2022-03, with the labels that each got.

#4918 fix: Pin express to 5.0.0-alpha.8
  package.json
  yarn.lock
Labels: bug, dependencies

#4928 feat(http): keep slashes in queryParams in redirects
  src/node/http.ts
  test/package.json
  test/unit/node/http.test.ts
  test/yarn.lock
Labels: testing

#4925 feat: add version of Code OSS to output
  src/node/constants.ts
  src/node/entry.ts
  test/unit/node/constants.test.ts
Labels: feature

#4929 chore: limit concurrency for build jobs
  .github/workflows/ci.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/docker.yaml
  .github/workflows/docs-preview.yaml
  .github/workflows/installer.yml
  .github/workflows/npm-brew.yaml
  .github/workflows/scripts.yml
Labels: ci, chore

#4923 feat: cli arg for file permission of socket
  src/node/app.ts
  src/node/cli.ts
  test/unit/node/app.test.ts
  test/unit/node/cli.test.ts
Labels: feature

#4943 fix: re-enable trivvy docker scan
  .github/workflows/ci.yaml
  .github/workflows/trivy-docker.yaml
Labels: security, ci, chore

#4953 testing: add new test for logLevels
  test/unit/node/cli.test.ts
Labels: testing

#4970 feat(testing): add test for optionDescriptions
  src/node/cli.ts
  test/unit/node/cli.test.ts
Labels: testing

#4972 feat(ci): publish dev builds to @coder/code-server-pr
  ci/steps/publish-npm.sh
Labels: ci

#4995 fix(ci): correctly download npm/docker artifacts
  .github/workflows/ci.yaml
  .github/workflows/docker.yaml
  .github/workflows/npm-brew.yaml
  ci/build/release-github-assets.sh
  ci/steps/docker-buildx-push.sh
  ci/steps/publish-npm.sh
  docs/MAINTAINING.md
Labels: ci

#5006 chore: update to minimist-list
  package.json
  yarn.lock
Labels: security, dependencies

#4996 refactor: checkout homebrew-core in action instead of script
  .github/workflows/npm-brew.yaml
  ci/steps/brew-bump.sh
Labels: ci

#5024 fix: source lib.sh in docker-buildx-push for tagging version
  ci/steps/docker-buildx-push.sh
Labels: ci

#5025 refactor(brew-bump): fix homebrew bump script
  .github/workflows/npm-brew.yaml
  ci/steps/brew-bump.sh
Labels: ci, chore

#5042 fix(workflows): docs-preview and npm job
  .github/workflows/ci.yaml
  .github/workflows/docs-preview.yaml
Labels: ci

#5045 docs(helm): add required env for docker-in-docker
  ci/helm-chart/values.yaml
Labels: docs

#5044 chore(rennovate): ignore updates for express
  renovate.json
Labels: dependencies, ci

#5046 chore(ci): disable docs-preview on forks
  .github/workflows/docs-preview.yaml
Labels: ci

#5049 fix(npm): write npm package name to file
  ci/steps/publish-npm.sh
Labels: chore
