Repository coder/code-server, pull requests merged in 2022-12, with the labels that each got.

#5827 feat(securitytxt): add security.txt
  src/browser/security.txt
  src/node/routes/index.ts
Labels: enhancement, security

#5772 release: 4.9.0
  .github/workflows/build.yaml
  .github/workflows/release.yaml
  .prettierignore
  CHANGELOG.md
  ci/helm-chart/Chart.yaml
  ci/helm-chart/values.yaml
  package.json
  src/node/wrapper.ts
  test/unit/node/wrapper.test.ts
Labels: rebase when passing

#5840 chore: update qs version
  package.json
  yarn.lock
Labels: dependencies

#5841 chore: update download artifacts in release
  .github/workflows/release.yaml
Labels: chore

#5868 fix: add VERSION to env in publish.yaml
  .github/workflows/publish.yaml
Labels: rebase when passing

#5852 fix: use npm and yarn consistently in build and release
  .github/workflows/release.yaml
  ci/build/build-release.sh
  ci/build/npm-postinstall.sh
Labels: rebase when passing

#5907 Added how to disable file downloads in faq
  docs/FAQ.md
Labels: docs
