Repository coder/code-server, pull requests merged in 2022-09, with the labels that each got.

#5541 chore: add npm followup comment
  ci/build/npm-postinstall.sh
Labels: rebase when passing, chore

#5542 Fix deb install instructions: ${VERSION}_foo
  docs/install.md
Labels: docs, rebase when passing

#5553 chore: move security workflows
  .github/workflows/ci.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/security.yaml
Labels: ci, chore

#5560 feat: add release workflow
  .github/workflows/release.yaml
  ci/build/release-github-assets.sh
  ci/build/release-github-draft.sh
  ci/lib.sh
  docs/MAINTAINING.md
  package.json
Labels: ci

#5601 chore: update vm2 to 3.9.11
  package.json
  yarn.lock
Labels: dependencies
