Repository coder/code-server, pull requests merged in 2022-01, with the labels that each got.

#4677 fix(ci): add environment to docs-preview
  .github/workflows/docs-preview.yaml
Labels: docs, ci

#4717 feat: add tests for node/settings.ts
  test/unit/node/settings.test.ts
Labels: testing, squash when passing

#4742 chore: use 1.14.7 follow-redirects
  package.json
  yarn.lock
Labels: security, dependencies

#4674 docs: fix typos in guide.md
  docs/guide.md
Labels: docs

#4787 chore(deps): update node-fetch and nanoid
  package.json
  yarn.lock
Labels: dependencies, chore
