Repository coder/code-server, pull requests merged in 2022-04, with the labels that each got.

#5068 fix: Exclude .deb files from release Docker image
  ci/release-image/Dockerfile
Labels: enhancement, chore

#5070 chore: remove file ext. from LICENSE
  LICENSE
  ci/build/build-release.sh
Labels: chore

#5075 docs: link upstream sync section in MAINTAINING to CONTRIBUTING
  docs/MAINTAINING.md
Labels: docs

#5079 docs: Update ios.md
  docs/ios.md
Labels: docs

#5078 docs: simplify termux installation process
  docs/termux.md
Labels: docs

#5106 chore: attempt to fix docker
  .github/workflows/docker.yaml
  package.json
Labels: ci, chore

#5133 fix: listening on IPv6 address not possible
  src/node/app.ts
  test/unit/node/app.test.ts
Labels: bug

#5134 feat(cli): support true for CS_DISABLE_FILE_DOWNLOADS
  src/node/cli.ts
  test/unit/node/cli.test.ts
Labels: enhancement
