Repository coder/code-server, pull requests merged in 2022-05, with the labels that each got.

#5142 refactor(heart): bind class methods and make beat async
  src/node/heart.ts
  src/node/routes/index.ts
  test/unit/node/heart.test.ts
Labels: testing

#5175 fix: Docker push
  .github/workflows/docker.yaml
Labels: ci

#5173 chore: configure git globally for brew publish
  .github/workflows/npm-brew.yaml
Labels: ci, chore

#5176 chore: update --help for disable-file-downloads
  src/node/cli.ts
Labels: chore

#5182 feat: add test for isFile when error
  test/unit/node/util.test.ts
Labels: testing

#5183 refactor(util): remove unused isObject function
  src/node/util.ts
Labels: chore

#5188 refactor: remove dead code
  src/common/util.ts
  src/node/app.ts
  src/node/constants.ts
  src/node/util.ts
  test/unit/common/util.test.ts
  test/unit/node/app.test.ts
  test/unit/node/constants.test.ts
Labels: chore

#5190 docs: rename master to main in all github doc links
  .tours/contributing.tour
  .tours/start-development.tour
  ci/build/npm-postinstall.sh
Labels: docs

#5194 Allow user Entrypoint scripts
  ci/release-image/Dockerfile
  ci/release-image/entrypoint.sh
Labels: enhancement

#5202 chore(deps): upgrade typescript to v4.6
  package.json
  yarn.lock
Labels: chore

#5209 Fix caddy installation docs
  docs/guide.md
Labels: docs
