Repository coder/code-server, pull requests merged in 2022-02, with the labels that each got.

#4814 feat: add test for hash with empty string
  src/node/util.ts
  test/unit/node/util.test.ts
Labels: testing

#4835 feat: add tests for update.ts
  test/unit/node/update.test.ts
  test/utils/helpers.ts
Labels: testing

#4864 fix: Slack community link
  docs/README.md
Labels: docs

#4868 chore: update follow-redirects resolution
  package.json
  yarn.lock
Labels: dependencies

#4879 docs: update sync vscode instructions
  docs/MAINTAINING.md
Labels: docs

#4875 fix: skip docs/npm workflows on forks
  .github/workflows/ci.yaml
  .github/workflows/docs-preview.yaml
Labels: docs, ci, chore

#4898 feat(testing): add new test for cli.ts
  test/unit/node/cli.test.ts
Labels: testing
