Repository coder/code-server, pull requests merged in 2022-08, with the labels that each got.

#5294 Update Install.md rsp install part
  docs/install.md
Labels: docs

#5432 feat: add test for EXTENSIONS_GALLERY
  test/integration/installExtension.test.ts
  test/utils/runCodeServerCommand.ts
Labels: testing, rebase when passing

#5434 feat: add --help integration test
  test/integration/help.test.ts
Labels: testing, rebase when passing

#5440 chore(ci): fix when npm job runs
  .github/workflows/ci.yaml
Labels: rebase when passing, chore

#5441 chore(testing): remove install/list tests
  test/integration/fixtures/wesbos.theme-cobalt2-2.1.6.vsix
  test/integration/installExtension.test.ts
  test/integration/listExtensions.test.ts
Labels: rebase when passing

#5442 [Security Issue] Avoid Exposing Ports without Authentication
  src/node/routes/index.ts
  src/node/routes/pathProxy.ts
Labels: rebase when passing

#5457 docs: add proxying to angular app
  docs/guide.md
  test/e2e/extensions.test.ts
Labels: docs, rebase when passing

#5462 feat(ci): semi-automate code-server-aur update
  .github/workflows/npm-brew.yaml
Labels: ci, rebase when passing

#5471 refactor(ci): combine publish workflows
  .github/workflows/docker.yaml
  .github/workflows/publish.yaml
Labels: rebase when passing

#5493 chore: fix npm publish logic
  ci/steps/publish-npm.sh
Labels: rebase when passing

#5519 refactor: drop db migration patch
  patches/disable-builtin-ext-update.diff
  patches/telemetry.diff
  patches/unique-db.diff
  test/e2e/codeServer.test.ts
Labels: rebase when passing, chore

#5522 release: 4.6.1
  CHANGELOG.md
  ci/build/release-prep.sh
  ci/helm-chart/Chart.yaml
  ci/helm-chart/values.yaml
  docs/collaboration.md
  docs/helm.md
  docs/manifest.json
  package.json
Labels: rebase when passing
